services:
  bot:
    container_name: tezaurs-bot
    restart: unless-stopped 
    build: .
    command: bun start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
      - /usr/app/dist
    depends_on:
      - postgres
    env_file:
      - .env
  postgres:
    container_name: tezaurs-postgres
    restart: unless-stopped  
    image: postgres:15-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_USER: tezaursbot
      POSTGRES_DB: tezaurs
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
