version: '3'

services:
  bot:
    container_name: tezaurs-bot
    restart: always
    build: .
    command: bun run start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
      - /usr/app/dist
    depends_on:
      - postgres
    environment:
      DB_URL: postgres://tezaursbot@postgres/tezaurs
    env_file:
      - .env
  postgres:
    container_name: tezaurs-postgres
    restart: always
    image: postgres:15-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_USER: tezaursbot
      POSTGRES_DB: tezaurs
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
